openapi: 3.0.3
info:
  title: Integron Cat Facts - OpenAPI 3.0
  contact:
    email: moha@moha.fi
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
    /facts:
      get:
        summary: Get a random cat fact
        parameters:
          - name: amount
            in: query
            required: true
            schema:
              type: integer
            description: The name of the city to get sunrise and sunset times for
            example: 5
        responses:
          '200':
            description: A JSON object containing cat facts
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      fact:
                        type: string
                        example: "Cats have a third eyelid called a haw."
                      id:
                        type: string
                        example: "63fb7ae0fcf661e5a09783aa"
          '400':
            description: Invalid data
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Invalid data"
          '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Internal server error"
        x-integron-steps:
          - name: catFacts
            type: http
            url: https://cat-fact.herokuapp.com/facts/random?amount=$.request.amount&animal_type=cat
            method: GET
            '200':
              output:
                response: $.body
              next: "arrayTransform"
          - name: arrayTransform
            type: array
            input: $.catFacts.response
            output:
              fact: $.text
              id: $._id
            next: ""
          - name: error
            type: error
            next: ""