openapi: 3.0.3
info:
  title: Integron Dog Facts - OpenAPI 3.0
  contact:
    email: moha@moha.fi
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
    /facts:
      get:
        summary: Get a random dog fact
        parameters:
          - name: amount
            in: query
            required: true
            schema:
              type: integer
            description: Number of facts to retrieve
            example: 5
        responses:
          '200':
            description: A JSON object containing dog facts
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          fact:
                            type: string
                            example: "Although it was once illegal to keep dogs as pets in Iceland's capital city, the laws have been relaxed."
                          id:
                            type: string
                            example: "9ed6fa65-8645-4cea-8124-372fc59788d2"
          '400':
            description: Invalid data
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Invalid data"
          '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Internal server error"
        x-integron-steps:
          - name: dogFacts
            type: http
            url: 'https://dogapi.dog/api/v2/facts?limit=$.request.amount'
            method: GET
            responses:
              '200':
                output:
                  response: $.body
                next: "arrayTransform"
          - name: arrayTransform
            type: array
            input: $.dogFacts.response.data
            output:
              fact: $.attributes.body
              id: $.id
              moha: null
            next: "removeNull"
          - name: removeNull
            type: removenull
            input: $.arrayTransform
            next: "responseMarshal"
          - name: responseMarshal
            type: object
            output:
              body:
                data: $.arrayTransform
            next: ""
          - name: error
            type: error
            next: ""